AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Real-Time Environmental Disaster Waste Tracking System

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9

Resources:
  WasteClassifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/waste-classifier/
      Handler: app.lambda_handler
      Events:
        WasteClassify:
          Type: Api
          Properties:
            Path: /classify
            Method: post

  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DisasterIncidents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: incident_id
          AttributeType: S
      KeySchema:
        - AttributeName: incident_id
          KeyType: HASH

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
